config/routes.rb
Rails.application.routes.draw do

  get 'images/upload'
  post 'images/create'
  delete 'images/destroy_all'
  post 'images/download_all'
  root to: 'images#index'
  resources :images do
    post :update, on: :member
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :file

  validates :file, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg'], size: { less_than: 10.megabytes , message: 'is too big' }

  paginates_per 10

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  include ActiveStorage::SendZip

  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all.page params[:page]

  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  def upload
    @image = Image.new

  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    parameters =create_params
    errors = []
    parameters[:files].each do |f|
      tmp = {:title => parameters[:title], :private => parameters[:private], :tags => parameters[:tags], :file => f}

      @image = Image.create(tmp)

      if !(@image.save)
        render action: :upload
      end


    end
    if errors.empty?
      redirect_to action: :index, notice: 'Image was successfully created.', uploaded_success: true
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update

    respond_to do |format|

      if @image.update(update_params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.file.purge
    @image.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Image.destroy_all
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download_all
    files = []
    imgs = Image.all
    imgs.each do |img|
      files << img.file
    end

    send_zip files
    # send_data @resume, type: "application/pdf", disposition: "attachment"

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def create_params
      params.require(:files)
      params.permit(:title, :tags, files: [])
    end

    # Only allow a list of trusted parameters through.
    def update_params
      params.require(:image)
      params.permit(:image => [:title, :tags])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Edit Image</h1>

<%= form_with(model: @image, :class => "form-horizontal center") do |form| %>
  <div class="form-group">
    <%= form.label(:title, "Image Title:") %>
    <%= form.text_field :title, :value => @image.title %>
  </div>
  <div class="form-group">
    <%= form.label(:tags, "Choose Tags:") %>
    <%= form.text_field :tags, :value => @image.tags%>
  </div>

  <%= submit_tag("Save", :class => "btn btn-light") %>
<% end %>

<%= link_to 'Back', @image , :class => "btn btn-light"%>
<%= button_to "Delete", { controller: :images, action: :destroy, id: @image.id }, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-light" %>

app/views/images/index.html.erb
<div class="container-fluid">
  <% if params[:uploaded_success] %>
    <div class="alert alert-success" role="alert">
      Files Uploaded Successfully!
    </div>
  <% end %>

  <%= paginate @images %>

  <div class="card-columns">
    <% @images.each do |img| %>
      <div class="card">
        <div class="card-block" >
          <%= image_tag img.file , :width => "100%" %>
          <div class="card-body">
            <p class="card-title"><%= img.title %></p>

            <% unless img.tags.empty? %>
              <p class="card-subtitle mb-2 text-muted">Tags: <%= img.tags %></p>
            <% end %>

              <%= link_to "View", image_path(img), :class => "btn btn-light" %>

          </div>

        </div>

      </div>


    <% end %>

  </div>

</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<div class="card-columns">

  <div class="card">
    <div class="card-block" >
      <%= image_tag @image.file , :width => "100%" %>
      <div class="card-body">
        <p class="card-title"><%= @image.title %></p>

        <% unless @image.tags.empty? %>
          <p class="card-subtitle mb-2 text-muted">Tags: <%= @image.tags %></p>
        <% end %>

        <%= link_to 'Edit', edit_image_path(@image), :class => "btn btn-light"%>
        <%= link_to "Download", rails_blob_path(@image.file, disposition: 'attachment'), :class => "btn btn-light" %>
        <%= link_to 'Back', root_path , :class => "btn btn-light"%>

      </div>

    </div>

  </div>
</div>

app/views/images/upload.html.erb
<h1>Upload an image</h1>

<%= form_with(url: images_create_path, method: "post",  :html => {:class => "form-horizontal center"}) do |form| %>
  <% if @image.errors.any?  %>
    <div class="alert alert-danger" role="alert">
      <%= @image.errors.full_messages.first %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label(:files, "Choose Files:") %>
    <%= form.file_field :files, multiple: true,  :required => true %>
    <%# , :accept => "application/jpeg, application/png, application/"%>
  </div>
  <div class="form-group">
    <%= form.label(:title, "Image Title:") %>
    <%= form.text_field :title %>
  </div>
  <div class="form-group">
    <%= form.label(:tags, "Choose Tags:") %>
    <%= form.text_field :tags%>
  </div>


  <%= submit_tag("Upload", :class => "btn btn-primary") %>



<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageRepo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item active">
            <%= link_to "Home", root_path, :class => "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Upload", images_upload_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Download All", { controller: :images, action: :download_all }, method: :post, data: { confirm: 'Are you sure?' }, :class => "nav-link btn"  %>
          </li>
          <li class="nav-item">
            <%= button_to "Delete All", { controller: :images, action: :destroy_all }, method: :delete, data: { confirm: 'Are you sure?' }, :class => "nav-link btn"  %>
          </li>
        </ul>
      </div>
    </nav>


    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Upload an image</h1>

<%= form_with(url: files_upload_path, method: "post",  :html => {:class => "form-horizontal center"}) do |form| %>
  <div class="form-group">
    <%= form.label(:file, "Choose File:") %>
    <%= form.file_field :file %>
  </div>
  <div class="form-group">
    <%= form.label(:title, "Image Title:") %>
    <div class="col-md-8">
      <%= form.text_area :title %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label(:tags, "Choose Tags:") %>
    <div class="col-md-8">
      <%= form.text_area :tags %>
    </div>
  </div>

  <%= submit_tag("Upload") %>



<% end %>

app/views/site/upload.html.erb
<h1>Upload an image</h1>

<%= form_with(url: images_create_path, method: "post",  :html => {:class => "form-horizontal center"}) do |form| %>
  <div class="form-group">
    <%= form.label(:file, "Choose File:") %>
    <%= form.file_field :file,  :required => true%>
  </div>
  <div class="form-group">
    <%= form.label(:title, "Image Title:") %>
    <%= form.text_field :title, :required => true %>
  </div>
  <div class="form-group">
    <%= form.label(:tags, "Choose Tags:") %>
    <%= form.text_field :tags%>
  </div>
  <div class="form-group">
    <%= form.label(:private, "Make Picture Public:") %>
    <%= form.check_box :private %>
  </div>

  <%= submit_tag("Upload", :class => "btn btn-primary") %>



<% end %>